### ISSUE TITLE
thumbnail not visible ?

### ISSUE THREAD

**Issue by NonoB** [slimndap/wp-theatre#240]
Hi, 

I'm using your Pluggin for Wordpress to the website :
http://www.avrilenseptembre.fr/agenda/

And I don't know why but the picture are not visible ?
<img width="458" alt="capture d ecran 2017-03-08 07 49 31" src="https://cloud.githubusercontent.com/assets/26269603/23693249/d3868506-03d3-11e7-8381-771600802160.png">
The height is 0 and I don't understand why ... What I need to change and where to correct this bug.

Thanks

**Comment by slimndap** [comment]
I think this is a theme issue, but I was able to overcome it by adding this to the CSS of your theme:

```css
.wpt_events .wp_theatre_event figure img {
    height: 150px;
}
```
