### ISSUE TITLE
Timetable runs off page

### ISSUE THREAD

**Issue by RaymondVanMelzen** [slimndap/wp-theatre#258]
Hi Jeroen,

I use the Timetable extension. I noticed that the timetable runs off the page when a production has many dates. I resolved that by putting the timetable in a div with style="overflow-x:auto;"

However, I did this by editting the class WPT_Productions_Timetable. Can you tell me how I can modify the timetable with a filter so I don't have to mess with the original code?

Regards,
Raymond

**Comment by slimndap** [comment]
This CSS limits the number of columns to 7:

```css
#voorstellingen .wpt_production_timetable tr th:nth-child(7) ~*, 
#voorstellingen .wpt_production_timetable tr td:nth-child(7) ~* {
    display: none;
}
```
